spring:
    application:
        name: Distant Class
    datasource:
        url: jdbc:mysql://localhost:3306/distant-class
        username: root
        password: abc1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: danhthanh3451@gmail.com
        password: qbubxgdgwfnpfbep
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 2000MB
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 244170825538-gfjr0s4hfes2euh8qjt5mseq2v0o8js5.apps.googleusercontent.com
                        client-secret: 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
                    github:
                        client-id: 0e415c66bab86a88d60e
                        client-secret: 1c726ff938a57bb38da145e6c2041daaf528a8ba

jwt:
    accessTokenExpiration: 36000000
    refreshTokenExpiration: 25200000

cloudinary:
    cloud-name: dosrtyzbs
    api-key: 149474742791446
    api-secret: 2xWYv3AJlZvRqtUzHEOyuimF5wI

dreamChasers:
    avatar: https://res.cloudinary.com/dhydbv51p/image/upload/v1727583503/dream_chasers_v2/wkn9oxyj0ks1madvhmxm.jpg

# logging:
#   level:
#     org:
#       springframework: DEBUG